= VDI Plugin Template
:icons: font

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository is a template repo for creating new VDI plugins.

For more details about the scripts themselves and their inputs and outputs see
the https://github.com/VEuPathDB/vdi-plugin-handler-server[VDI Plugin Handler Server]
readme.

== Usage

=== Demonstration

==== Prerequisites

* Docker
* sshuttle

==== Setup

. Copy the link:example.env[] file from the root of this repo to a new file
  named `.env` in the repository root directory. +
  The `.env` file will be ignored by Git by default.
. Edit the new `.env` file by doing the following at minimum:
.. Provide a valid `LDAP_SERVER` variable value.
.. Provide a valid `ORACLE_BASE_DN` variable value.
.. Provide the database TNS name and user credentials for at least one of the
   database configuration blocks provided.
.. Comment out any unused database configuration blocks.
+
[NOTE]
--
No connection to any databases will be attempted by the VDI Plugin Handler
Server or any of the included example plugin scripts.  The database connection
details are simply required to pass server startup config validation.

The TNS name is the only value that is required to be correct, the credential
variables may be junk strings.
--

==== Run the Example

--
. Start up sshuttle (see the VEuPathDB confluence documentation for running a
service locally).
. Start the plugin service using the `start` target in the included `makefile`.
--

Example::
+
[source, shell-session]
----
$ sshuttle ...
$ make start
----

===== Shell Access

Shell access into the plugin container can be gained quickly by using the
`shell` target in the included `makefile`:

[source, shell-session]
----
$ make shell
----


===== Shutdown

To stop the plugin service when it is no longer needed, use the `stop` target
in the included `makefile`:

[source, shell-session]
----
$ make stop
----

=== Creating a New Plugin Handler

To use this repository, click the green "Use this template" button near the top
right of the repository source file listing table and create a new repository
for your handler.

This repository follows the normal steps as outlined in the VEuPathDB Confluence
doc titled "Deploy Containerized Services for Local Development".

==== Script Development

===== What's Included

====== Resources

Included in the base container are the following resources:

* PostgreSQL 15
* Python3
* Perl
* Java 21
* Maven
* Ant
* Oracle Instant Client 21.11

====== Environment Variables

* `GUS_HOME`
* `PROJECT_HOME`
* `TEMPLATE_DB_NAME`
* `TEMPLATE_DB_USER`
* `TEMPLATE_DB_PASS`

===== Getting Set Up

. Copy the file `local-dev.env` to a new file named simply `.env`.  This file
  will be automatically read by Docker Compose when the stack is spun up.
. Fill in the environment variables in the `.env` file with actual values for
  the target application database.


===== Building the Image

. Run `make build` to build or rebuild the image with your changes.


===== Running the Plugin Container

. Run `make shell` to tunnel into a new, temporary plugin container where you
  can execute your scripts.  The plugin container will be destroyed when exiting
  the tunnelled shell.

[IMPORTANT]
--
The internal PostgreSQL instance is not started automatically.  If you are
developing a plugin that relies on the internal Postgres instance, it will need
to be manually started before doing local script testing.

[source, console]
----
$ /usr/lib/postgresql/15/bin/pg_ctl start
----
--
